### ISSUE TITLE
Could you add to armaservermonitor.exe ability to log network usage parameters?

### ISSUE THREAD

**Issue by Zealot111** [fred41/ASM#12]
Now armaservermonitor.exe doesn't log network usage parameters. If you won't add these parameters, could you please share sourcecode of armaservermonitor.exe to allow us to add these parameters outselves?

**Comment by fred41** [comment]
Please read the reasons for project termination in related bis forum (initial post) and try to understand why i don't do anything more, before not a serious monitoring interface is implemented in arma server.
