### ISSUE TITLE
Transparency bug

### ISSUE THREAD

**Issue by stargatefreak** [fred41/ASM#14]
Once you make it transparent you have no way to make it opaque.

Every time you try to right click on the program it right clicks on the window behind it.

**Comment by Crazy538** [comment]
Just ran into this myself. Curiosity got the better of me and now I'm stuck with it in an opaque state.

Not the end of the world (using remote connect and I only did it on the host side) but a bit of a pain.

**Comment by fred41** [comment]
... just try to hit a non transparent pixel (with RMB) in ASM-window, colored letters for example ...

I know it may be hard sometimes, so treat it as somthing like a build-in minigame ;)

**Comment by fred41** [comment]
... just try to hit a non transparent pixel (with RMB) in ASM-window, colored letters for example ...

I know it may be hard sometimes, so treat it as somthing like a build-in minigame ;)

Greets,
Fred41
